version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/home-assistant"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/sonarr"
    schedule:
      interval: "daily"
